version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows/
    schedule:
      interval: monthly
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
