image: continuumio/miniconda3:latest

before_script:
  - conda config --add channels conda-forge
  - conda install -y mamba -c conda-forge
  - conda init bash
  - source $HOME/.bashrc
  - mamba env update -f environment-dev.yml -n base
  - pip install .

test:
  stage: test
  script:
  - cd docs/
  - python3 -m sphinx -b html . _build
  only:
  - branches
  except:
  - main

pages:
  stage: deploy
  script:
  - cd docs/
  - python3 -m sphinx -b html . _build
  - cd ..
  - mkdir public/
  - cp -r docs/_build/* public/
  artifacts:
    paths:
    - public
  only:
  - main
