default_language_version:
    python: python3

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: [ '--py39-plus' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: setup.cfg
      - id: end-of-file-fixer
        exclude: setup.cfg
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-json
      - id: pretty-format-json
        args: [ '--autofix', '--no-ensure-ascii', '--no-sort-keys' ]
        exclude: .ipynb
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
        exclude: conda/xscen/meta.yaml
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-inline-touching-normal
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        exclude: ^docs/
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [ 'flake8-rst-docstrings' ]
        args: [ '--config=setup.cfg' ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ '--settings-file=setup.cfg' ]
        exclude: ^docs/
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [ '--config=setup.cfg' ]
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc
        additional_dependencies: [ 'black==23.9.1' ]
        exclude: config.py
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [ '--config-file=.yamllint.yaml' ]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-pyupgrade
        args: [ '--py39-plus' ]
      - id: nbqa-black
        args: [ '--target-version=py39' ]
      - id: nbqa-isort
        args: [ "--settings-file=setup.cfg" ]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: .cruft.json|docs/notebooks
        args: [ '--baseline=.secrets.baseline' ]
#  Currently commented because Git needs to be updated on our work environment.
#  - repo: https://github.com/mgedmin/check-manifest
#    rev: "0.49"
#    hooks:
#      - id: check-manifest
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
