default_language_version:
    python: python3

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: setup.cfg
      - id: end-of-file-fixer
        exclude: setup.cfg
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
      - id: debug-statements
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-inline-touching-normal
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ^docs/
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [ 'flake8-rst-docstrings' ]
        args: [ '--config=setup.cfg' ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ '--profile=black', '--filter-files' ]
        exclude: ^docs/
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [ '--config=setup.cfg' ]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [ '--config-file=.yamllint.yaml' ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline=.secrets.baseline', '--exclude-files=.cruft.json' ]
#  Currently commented because Git needs to be updated on our work environment.
#  - repo: https://github.com/mgedmin/check-manifest
#    rev: "0.48"
#    hooks:
#      - id: check-manifest
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
