version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      - pip install . --no-deps
    pre_build:
      - sphinx-apidoc -o docs/apidoc --private --module-first xscen
      - env SKIP_NOTEBOOKS=1 sphinx-build -b linkcheck docs/ _build/linkcheck

conda:
  environment: environment-dev.yml
