version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      - make translate
      - pip install . --no-deps
    pre_build:
      - sphinx-apidoc -o docs/apidoc --private --module-first src/xscen
      - env SKIP_NOTEBOOKS=1 sphinx-build -b linkcheck docs/ _build/linkcheck || true
      - env SKIP_NOTEBOOKS=1 sphinx-build -M gettext docs docs/_build
#    post_build:
#      - rm -rf docs/notebooks/_data

conda:
  environment: environment-dev.yml
