name: xscen
channels:
  - conda-forge
dependencies:
  - python >=3.8
  # Don't forget to sync the changes here with environment-dev.yml!
  # Main packages
  - cartopy
  - cftime
  - clisops
  - dask
  - flox
  - fsspec
  - geopandas
  - h5netcdf
  - intake
  - intake-esm >=2022.9.18
  - matplotlib
  - netCDF4
  - numpy
  - pandas!=1.5.3
  - pyyaml
  - rechunker
  - shapely
  - xarray
  - xclim >=0.37
  - xesmf >=0.7
  - zarr
  # To avoid bugs
  # See https://github.com/esmf-org/esmf/issues/115
  # we add this "dependency" so the following pip install doesn't install anything else than xscen
  - pytest-json-report
  # Opt
  - nc-time-axis >=1.3.1
  - pyarrow >=1.0.0
  - pip
