name: xscen
channels:
  - conda-forge
dependencies:
  - python >=3.9
  # Don't forget to sync the changes here with environment-dev.yml!
  # FIXME
  - pydantic <2.0  # See: https://github.com/intake/intake-esm/issues/617
  # Main packages
  - cartopy
  - cftime
  - cf_xarray >=0.7.6
  - clisops >=0.10
  - dask
  - flox
  - fsspec
  - geopandas
  - h5netcdf
  - intake
  - intake-esm >=2022.9.18
  - matplotlib
  - netCDF4
  - numpy
  - pandas >= 2
  - parse
  - pygeos
  - pyyaml
  - rechunker
  - shapely
  - xarray
  - xclim >=0.43.0
  - xesmf >=0.7
  - zarr
  # Opt
  - nc-time-axis >=1.3.1
  - pyarrow >=1.0.0
  - pip
