name: xscen
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and setup.py!
  # Also consider updating the list in xs.utils.show_versions if you add a new package.
  # Main packages
  - cartopy
  - cftime
  - cf_xarray >=0.7.6
  - clisops >=0.10
  - dask
  - flox
  - fsspec
  - geopandas
  - h5netcdf
  - h5py
  - intake-esm >=2023.07.07
  - matplotlib
  - netCDF4
  - numcodecs
  - numpy
  - pandas >=2.2
  - parse
  - pyyaml
  - rechunker
  - scipy
  - shapely >=2.0
  - sparse
  - toolz
  - xarray >=2023.11.0
  - xclim >=0.48.2
  - xesmf >=0.7
  - zarr
  # To install from source and get translations
  - babel
  # Opt
  - nc-time-axis >=1.3.1
  - pyarrow >=1.0.0
  - pip
