name: xscen
channels:
  - conda-forge
dependencies:
  - python >=3.9
  # Don't forget to sync the changes here with environment-dev.yml!
  # Main packages
  - cartopy
  - cftime
  - cf_xarray >=0.7.6
  - clisops >=0.10
  - dask
  - flox
  - fsspec
  - geopandas
  - h5netcdf
  - h5py
  - intake-esm >=2023.07.07
  - matplotlib
  - netCDF4
  - numpy
  - pandas >= 2
  - parse
  - pyyaml
  - rechunker
  - shapely >= 2
  - sparse
  - toolz
  - xarray
  - xclim >=0.43.0
  - xesmf >=0.7
  - zarr
  # Opt
  - nc-time-axis >=1.3.1
  - pyarrow >=1.0.0
  - pip
