name: xscen
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  - pip >=25.0
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Also consider updating the list in xs.utils.show_versions if you add a new package.
  # Main packages
  - cartopy >=0.23.0
  - cftime
  - cf_xarray >=0.7.6
  - clisops >=0.16.1
  - dask >=2024.8.1
  - flox
  - fsspec
  - geopandas >=1.0
  - h5netcdf
  - h5py
  - intake-esm ==2025.2.3
  - matplotlib >=3.6
  - netcdf4
  - numcodecs <0.16.0
  - numpy >=1.24
  - openpyxl
  - pandas >=2.2
  - parse
  - pyarrow >=15.0.0
  - pyproj
  - pyyaml
  - rechunker >=0.5.3
  - scipy >=1.11.0
  - shapely >=2.0
  - sparse
  - toolz
  - xarray >=2023.11.0, !=2024.6.0
  - xclim >=0.58, <0.59
  - xsdba >=0.4.0
  - zarr >=2.13, <3
  # Opt
  - nc-time-axis >=1.3.1
  - xesmf >=0.7, !=0.8.8
  # To install from source
  - flit >=3.10.1,<4.0
