name: xscen
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  # FIXME: These entries require versions
  # Don't forget to sync the changes here with environment-dev.yml!
  # Main packages
  - cftime
  - clisops
  - dask
  - esmpy <8.4
  - geopandas
  - pandas
  - rechunker
  - shapely
  - xarray
  - xclim >=0.37
  - xesmf >=0.6.2
  - pyyaml
  - intake-esm >=2022.9.18
  # Plotting
  - cartopy
  - matplotlib
  - nc-time-axis >=1.3.1
  # IO
  - h5py
  - netCDF4
  - pyarrow
  - zarr
  - pip
