{% set name = "xscen" %}

package:
  name: {{ name|lower }}
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  path: ../../

channels:
  - conda-forge
  - defaults

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - cartopy
    - cftime
    - cf_xarray >=0.7.6
    - clisops >=0.10
    - dask-core
    - flox
    - fsspec <2023.10.0
    - geopandas
    - h5netcdf
    - h5py
    - intake-esm >=2023.07.07
    - matplotlib
    - netCDF4
    - numpy
    - pandas >= 2
    - parse
    - pyyaml
    - rechunker
    - shapely >= 2
    - sparse <=0.14
    - toolz
    - xarray <2023.11.0  # FIXME: Remove when pandas 2.2 is released and xclim is fixed.
    - xclim >=0.46.0
    - xesmf >=0.7
    - zarr
    # Opt
    - nc-time-axis >=1.3.1
    - pyarrow >=1.0.0

test:
  imports:
    - xscen
  commands:
    - pip check
  requires:
    - pip
    - pytest-json-report  # Added due to a bug in esmpy. See: https://github.com/esmf-org/esmf/issues/115

about:
  home: https://github.com/Ouranosinc/xscen
  summary: A climate change scenario-building analysis framework, built with xclim/xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    # GitHub.com
    - Zeitsperre
    - RondeauG
    - aulemahal
    - juliettelavoie
