name: "Bump Patch Version"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .cruft.json
      - .editorconfig
      - .flake8
      - .github/**.yml
      - .gitignore
      - .gitlab-ci.yml
      - .gitmodules
      - .pre-commit-config.yaml
      - .secrets.baseline
      - .yamllint.yaml
      - AUTHORS.rst
      - CHANGES.rst
      - CONTRIBUTING.rst
      - MANIFEST.in
      - Makefile
      - conda/xscen/*.yaml
      - docs/*.py
      - docs/*.rst
      - docs/notebooks
      - environment-dev.yml
      - environment.yml
      - pyproject.toml
      - setup.cfg
      - setup.py
      - templates
      - tests/*.py
      - tox.ini
      - xscen/__init__.py

jobs:
  bump_patch_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Config Commit Bot
        run: |
          git config --local user.email "bumpversion[bot]@ouranos.ca"
          git config --local user.name "bumpversion[bot]"
      - name: Current Version
        run: echo "current_version=$(grep -E '__version__'  xscen/__init__.py | cut -d ' ' -f3)"
      - name: Bump Patch Version
        run: |
          python -m pip install bump-my-version
          echo "Bumping version"
          bump-my-version bump --tag patch
          echo "new_version=$(grep -E '__version__'  xscen/__init__.py | cut -d ' ' -f3)"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          force: false
          github_token: ${{ secrets.BUMPVERSION_TOKEN }}
          branch: ${{ github.ref }}
