# This workflow requires a personal access token named `BUMP_VERSION_TOKEN` with the following privileges:
# - Contents: Read and Write
# - Metadata: Read-Only
# - Pull Requests: Read and Write

name: "Bump Patch Version"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .cruft.json
      - .editorconfig
      - .flake8
      - .github/**.yml
      - .gitignore
      - .gitlab-ci.yml
      - .gitmodules
      - .pre-commit-config.yaml
      - .secrets.baseline
      - .yamllint.yaml
      - AUTHORS.rst
      - CHANGES.rst
      - CONTRIBUTING.rst
      - MANIFEST.in
      - Makefile
      - conda/xscen/*.yaml
      - docs/*.py
      - docs/*.rst
      - docs/notebooks
      - environment-dev.yml
      - environment.yml
      - pyproject.toml
      - setup.py
      - templates
      - tests/*.py
      - tox.ini
      - xscen/__init__.py

permissions:
  contents: read

jobs:
  bump_patch_version:
    name: Bump Patch Version
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.x"
      - name: Config Commit Bot
        run: |
          git config --local user.email "bumpversion[bot]@ouranos.ca"
          git config --local user.name "bumpversion[bot]"
      - name: Install bump-my-version
        run: |
          python -m pip install "bump-my-version>=0.17.1"
      - name: Current Version
        run: |
          bump-my-version show current_version
          CURRENT_VERSION="$(grep -E '__version__'  xscen/__init__.py | cut -d ' ' -f3)"
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Conditional Bump Version
        run: |
          if [[ ${{ env.CURRENT_VERSION }} =~ -dev(\.\d+)? ]]; then
            echo "Development version (ends in 'dev(\.\d+)?'), bumping 'build' version"
            bump-my-version show new_version --increment build
          else
            echo "Version is stable, bumping 'patch' version"
            bump-my-version show new_version --increment patch
          fi
      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: false
          github_token: ${{ secrets.BUMP_VERSION_TOKEN }}
          branch: ${{ github.ref }}
