name: Build and upload conda packages

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be built and uploaded'
        required: true
        type: string
      label:
        description: 'The type of release'
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  conda_deployment_with_tag:
    name: Build conda package with Python${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.tag == '' }}
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.tag != '' }}
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Setup Conda (Micromamba) with Python${{ matrix.python-version }}
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          channels: conda-forge,defaults
          extra-specs: |
            python=${{ matrix.python-version }}
            anaconda-client
            conda-build
      - name: Conditionally set label
        uses: haya14busa/action-cond@v1
        id: label
        with:
          cond: ${{ github.event_name == 'workflow_dispatch' }}
          if_true: ${{ github.event.inputs.label }}
          if_false: "auto"
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: conda/xscen
          python-version: ${{ matrix.python-version }}
          user: Ouranosinc
          label: ${{ steps.label.outputs.value }}
          token: ${{ secrets.ANACONDA_TOKEN }}
